# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-22 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170622_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 6, 22, 22, 21, 8, 202000), upload_to=b'org/%Y%m', verbose_name='\u5934\u50cf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default=b'teacher/default.png', upload_to=b'teacher/%Y%m', verbose_name='logo'),
        ),
    ]
