# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-20 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170619_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverfyrecord',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u53ef\u7528'),
        ),
    ]
