# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverfyrecord_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverfyrecord',
            name='send_type',
            field=models.CharField(choices=[(b'register', '\u6ce8\u518c'), (b'forget', '\u627e\u56de\u5bc6\u7801'), (b'update', '\u4fee\u6539\u90ae\u7bb1')], max_length=16, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b'),
        ),
    ]
